apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.nameSpace }}
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.internal }}
  selector:
    app: guestbook
    tier: frontend