apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.nameSpace }}
  annotations:
    autoscaling.alpha.kubernetes.io/HPA: "redis-slave-hpa"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: {{ .Values.image.deploy }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: {{ .Values.service.internal }}