apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: {{ .Values.nameSpace }}
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: redis
    role: master
    tier: backend
