apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: {{ .Values.nameSpace }}
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: redis
    role: slave
    tier: backend