apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  namespace: {{ .Values.nameSpace }}
  annotations:
    autoscaling.alpha.kubernetes.io/HPA: "redis-slave-hpa"
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: redis-master
        image: {{ .Values.image.master }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        ports:
        - containerPort: {{ .Values.service.port }}