apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: {{ .Values.nameSpace }}
  annotations:
    autoscaling.alpha.kubernetes.io/HPA: "redis-slave-hpa"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: redis-slave
        image: {{ .Values.image.slave }}
        resources:
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: {{ .Values.service.port }}